### ISSUE TITLE
idea-ultimate: Stripping out other arches

### ISSUE THREAD

**Issue by samip5** [Blackburn29/blackburn29-overlay#10]
Why is the ebuild stripping out arm64?

https://github.com/Blackburn29/blackburn29-overlay/blob/513c00fd41410e547b5a9209799a2ebe1e98a21a/dev-util/idea-ultimate/idea-ultimate-2024.2.0.1.ebuild#L52L65

**Comment by Blackburn29** [comment]
I don’t use arm so I do not maintain the arm builds. You’re welcome to submit a PR
