### ISSUE TITLE
License in toolbox

### ISSUE THREAD

**Issue by samip5** [Blackburn29/blackburn29-overlay#8]
I just noticed the wierd way you're specifying the license resulting in:
- dev-util/jetbrains-toolbox-2.3.0::blackburn29 (masked by: || ( ) yFiles yourkit license(s))

So emerge is not sure about it or something like that?

**Comment by Blackburn29** [comment]
> I just noticed the wierd way you're specifying the license resulting in:
> 
> * dev-util/jetbrains-toolbox-2.3.0::blackburn29 (masked by: || ( ) yFiles yourkit license(s))
> 
> So emerge is not sure about it or something like that?

I will check on this and get back to you. Unfortunately the Jetbrains licenses are pretty strict and are a mixed bag. Ill see what I can do.

**Comment by Blackburn29** [comment]
@samip5 I have updated the packages to use the gentoo-bundled versions of the Jetbrains licenses

**Comment by samip5** [comment]
It cannot be done like you're doing as can't do += in sh so just don't close the ", then it can be multi line.

Eg upstream gentoo has idea-community as an example: https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-util/idea-community/idea-community-2024.2.0.1.ebuild#n18

**Comment by Blackburn29** [comment]
> It cannot be done like you're doing as can't do += in sh so just don't close the ", then it can be multi line.
> 
> Eg upstream gentoo has idea-community as an example: https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-util/idea-community/idea-community-2024.2.0.1.ebuild#n18

This is untrue. License can be appended in the way that I do it. There are plenty of mainline ebuilds that do it this way.

**Comment by samip5** [comment]
Can you explain why I get it complaining about `yFiles yourkit` instead of the ebuild listed licenses? Where does that come from?
